server.port=8815
spring.application.name=payment-service

# Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Database Configuration (H2)
spring.datasource.url=jdbc:h2:mem:paymentdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Kafka Configuration
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:kafka-hiepweb2-nguyenvuhiep401-b7ce.h.aivencloud.com:19105}
spring.kafka.properties.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=SCRAM-SHA-256
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_SASL_USERNAME:avnadmin}" password="${KAFKA_SASL_PASSWORD:AVNS_ZlTe0rPhFWbpWPic41k}";
spring.kafka.properties.ssl.truststore.location=d:/Bai Tap/java-project/e-commerce-microservices-master/truststore.jks
spring.kafka.properties.ssl.truststore.password=${KAFKA_TRUSTSTORE_PASSWORD:mypassword}
spring.kafka.properties.ssl.truststore.type=JKS
spring.kafka.consumer.group-id=payment-group-v2
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.type.mapping=com.rainbowforest.orderservice.event.OrderCreatedEvent:com.rainbowforest.paymentservice.event.OrderCreatedEvent

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
